### PR TITLE
Wizard Form Review - DON'T MERGE

### PR DESCRIPTION
**Pull request by danigomez**
Related to redux-autoform/redux-autoform#36

### CODE REVIEW

**Comment by andrerpena** [comment]
Congrats for your work. I'll review this as soon as I can

**Comment by andrerpena** [comment]
I promise I'll take a look at it today :)

**Comment by JonatanSalas** [comment]
@danigomez you should resolve some conflicts with this branch!

**Comment by danigomez** [comment]
Conflicts solved!! Rejoice!  :smile:

**Comment by danigomez** [comment]
Hey @andrerpena !!, Could you review this??? :smile:

**Comment by JonatanSalas** [comment]
@andrerpena I will merge it because we need it to release a beta. Then you can check it! :smile: I trust on @danigomez work and I have reviewed it :+1:

**Comment by andrerpena** [comment]
@danigomez and @JonatanSalas! Congrats on this work. I'll be back on this this Thursday. Sorry I've been away!

**Comment by JonatanSalas** [comment]
@andrerpena don't worry! :smile:

**Pull request merged**
