### PR TITLE
Revert "Make the component themable. Additionally, when I working on this ver…"

### PR DESCRIPTION
**Pull request by andrerpena**
The variables used by the components LESS files were being defined in the Demo. Which doesn't make sense. The demo shouldn't be **required** for the library to work.

Thanks for your work anyways. I'll revise it.

### CODE REVIEW

**Comment by JonatanSalas** [comment]
@andrerpena excuse me!

**Comment by andrerpena** [comment]
Also, the Button.less file was referring specifically to the Add button in the ArrayContainer.. So, this style should be in the ArrayContainerl.less

**Comment by andrerpena** [comment]
@JonatanSalas Don't worry. These kinds of things are hard to spot without actually opening the project and looking into it.

**Comment by JonatanSalas** [comment]
@andrerpena because of that I merge it, I was going to run the demo to see the changes better.. bad mine.

**Comment by andrerpena** [comment]
@JonatanSalas , Zhang, that worked on the PR actually works here and here's right next to me :). Haha.. He's still learning. It was easier for me to see the problem because he's here explaining to me what he did. Don't feel bad man!

**Comment by JonatanSalas** [comment]
jaja I don't feel bad @andrerpena! What I say it's that I have to look better :P It's nice to recognize when you make a mistake xD

**Pull request merged**
